#!/bin/sh
# Run BLE and log privacy tests on the host, without an ARM toolchain or hardware.
set -eu
COREX_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
COREX_RUSTC=$(rustup which --toolchain 1.95.0 rustc)
COREX_HOST=$("$COREX_RUSTC" -vV | sed -n 's/^host: //p')
if [ -z "$COREX_HOST" ]; then
    echo "Unable to determine the Rust host target" >&2
    exit 1
fi

# This library has no distributed lockfile. Remove only a lockfile generated by
# this invocation; preserve any file that already exists or becomes tracked.
COREX_LOCK_REL=source/corex-rmk-upstream/rmk/Cargo.lock
COREX_REMOVE_LOCK=false
if [ ! -e "$COREX_ROOT/$COREX_LOCK_REL" ] &&
    ! git -C "$COREX_ROOT" ls-files --error-unmatch -- "$COREX_LOCK_REL" >/dev/null 2>&1; then
    COREX_REMOVE_LOCK=true
fi
corex_cleanup() {
    if [ "$COREX_REMOVE_LOCK" = true ] &&
        ! git -C "$COREX_ROOT" ls-files --error-unmatch -- "$COREX_LOCK_REL" >/dev/null 2>&1; then
        rm -f -- "$COREX_ROOT/$COREX_LOCK_REL"
    fi
}
trap corex_cleanup 0

for COREX_TEST_FILTER in ble::battery_service usb::log_privacy_tests; do
    rustup run 1.95.0 cargo test \
        --manifest-path "$COREX_ROOT/source/corex-rmk-upstream/rmk/Cargo.toml" \
        --no-default-features --features std,log,_ble,split,vial \
        --target "$COREX_HOST" --target-dir "$COREX_ROOT/build/tests/ble" \
        --lib "$COREX_TEST_FILTER"
done
